// src/components/portal/AcmeFooter.tsx
/**
 * AcmeFooter — barra de pie de página corporativa ACME.
 *
 * Componente sin props, reutilizable en AcmeLandingPage y AcmeHomePage.
 * Todos los enlaces son no-op intencionadamente (maqueta visual).
 */
export function AcmeFooter() {
  return (
    <footer className="bg-gray-900 text-gray-400 py-3 z-20 relative">
      <div className="max-w-7xl mx-auto px-4 text-center text-xs space-x-3">
        <span>© {new Date().getFullYear()} Acme Corp</span>
        <span>·</span>
        <a href="#" onClick={(e) => e.preventDefault()} className="hover:text-white">
          Política de cookies
        </a>
        <span>·</span>
        <a href="#" onClick={(e) => e.preventDefault()} className="hover:text-white">
          Accesibilidad
        </a>
        <span>·</span>
        <a href="#" onClick={(e) => e.preventDefault()} className="hover:text-white">
          Aviso Legal
        </a>
      </div>
    </footer>
  );
}

// src/app/features/acme/acme-footer/acme-footer.component.ts
import { Component } from '@angular/core';

/**
 * Barra de pie de página corporativa ACME.
 * Equivalente a AcmeFooter.tsx (React). Sin props — reutilizable en landing y home.
 */
@Component({
  selector: 'app-acme-footer',
  template: `
    <footer class="bg-gray-900 text-gray-400 py-3 z-20 relative">
      <div class="max-w-7xl mx-auto px-4 text-center text-xs space-x-3">
        <span>&copy; {{ currentYear }} Acme Corp</span>
        <span>·</span>
        <a href="#" (click)="$event.preventDefault()" class="hover:text-white">Política de cookies</a>
        <span>·</span>
        <a href="#" (click)="$event.preventDefault()" class="hover:text-white">Accesibilidad</a>
        <span>·</span>
        <a href="#" (click)="$event.preventDefault()" class="hover:text-white">Aviso Legal</a>
      </div>
    </footer>
  `,
})
export class AcmeFooterComponent {
  readonly currentYear = new Date().getFullYear();
}
